### ISSUE TITLE
Output styling issues

### ISSUE THREAD

**Issue by mrchristian** [NFDI4Culture/CPS-Demo#15]
- [x] give the title a background or a border to make it more readable

- [ ] style links with boxes or colour

- [ ] put the content of index.qmd on page ii

**Comment by mrchristian** [comment]
Please add notes about how to change the PDF page layout from print pagination style to screen PDF style. Here I mean the left and right magin thing. Its good we use the Screen PDF, but need to know how to revert things.

**Comment by calnfynn** [comment]
Add `geometry` settings and `classoption: openany` to quarto.yml in order to get a screen PDF (See here for more details: https://github.com/NFDI4Culture/publishing-documentation/blob/main/docs/quarto-guide.md#pdf-layoutstyling).
Delete the `geometry` and `classoption` parts to go back to default print pagination.
